sign-commit = true
sign-tag = true
tag = true
push = true
publish = false
dev-version = false
consolidate-commits = false
consolidate-pushes = true
tag-name = "{{crate_name}}-v{{version}}"
pre-release-commit-message = "chore({{crate_name}}): Release {{version}}"
allow-branch = ["main"]
